[project]
name = "x-bot"
version = "0.0.1"
description = "Small ð• bot"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "apscheduler>=3.11.1",
    "chromadb>=0.3.23",
    "feedparser>=6.0.12",
    "openai>=2.7.0",
    "pydantic>=2.12.3",
    "python-dotenv>=1.2.1",
    "pyyaml>=6.0.3",
    "requests>=2.32.5",
    "selenium>=4.38.0",
    "twscrape>=0.17.0",
    "webdriver-manager>=4.0.2",
]
